### ISSUE TITLE
duration

### ISSUE THREAD

**Issue by bw1984** [yomotsu/camera-controls#1]
is there any way to set the duration?

**Comment by yomotsu** [comment]
@bw1984 unfortunately, duration is not supported, since it relies on damping to move.
https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L439-L441

You can change `dampingFactor` to move faster/slower.
e.g. `control.dampingFactor=0.5`
https://github.com/yomotsu/camera-controls/blob/master/src/camera-controls.js#L33
