### ISSUE TITLE
Mesh was clipped when called setOrbitPoint in OrthographicCamera

### ISSUE THREAD

**Issue by LuckyTeresa** [yomotsu/camera-controls#325]
### Describe the bug

Mesh was clipped when called setOrbitPoint in OrthographicCamera

### To Reproduce

Using the offical example click-to-set-orbit-point.html to reproduce this issue.
1.open click-to-set-orbit-point.html in editor
2. repleace the PerspectiveCamera to an OrthographicCamera in line 25,
3. open in browser and rotate the green cube randomly

### Code

```js
// const camera = new THREE.PerspectiveCamera( 60, width / height, 0.01, 100 );
const camera = new THREE.OrthographicCamera( - width /2, width / 2, height / 2, - height / 2, 0.01, 100 );
```

### Expected behavior

mesh is not being clipped.

### Screenshots or Video

![企业微信截图_16696288607016](https://user-images.githubusercontent.com/33902263/204253248-f5991202-3652-46a3-8510-1a652f0469fb.png)

### Device

Desktop

### OS

Windows

### Browser

Chrome

**Comment by yomotsu** [comment]
If you are using an old version of camera-contorls, please update to the latest.
I recently fixed an OrbitControls problem.

**Comment by LuckyTeresa** [comment]
The latest version also has this problem

https://user-images.githubusercontent.com/33902263/204412406-d8684c19-7e6e-488b-81e2-4dfedebdb155.mp4

**Comment by yomotsu** [comment]
The clipping is caused by the NEAR param of OrthographicCamera, which is the 3rd argument of OrthographicCamera class.
The part is clipped if the green mesh is closer than the near-clipping plane.

In fact, if I grab the mesh to be closer by clicking the nearest point, then, it's clipped.
https://user-images.githubusercontent.com/212837/204414846-e7404805-3d2b-46b2-81ed-74f7101d8771.mp4

To reduce the problem, dolly out the cameraControls, or set a smaller number to near.
(I think this is not cameraControls problem)

**Comment by LuckyTeresa** [comment]
Thanks for your advice, I'll try it.
