### ISSUE TITLE
How to stop camera moving?

### ISSUE THREAD

**Issue by cryingnavi** [yomotsu/camera-controls#334]
### Is your feature request related to a problem? Please describe.

I implemented camera movement in wasd as shown in the example. Is there any way to prevent further movement when it touches an object such as a wall?

Keyboard events are handled as follows:
aKey.addEventListener('holding', (event) => {
      this.controls.truck(-this.moveSpeed * event.deltaTime, 0, false);
});

**Comment by yomotsu** [comment]
Thanks for using camera-controls.
However, I think your issue is app specific question.
（Please understand that this is not a well-sponsored project nor a contract work.
Basically, Issues are for bug reports or feature requests.

I can't answer every single app-specific question from all users.
If you wish to have additional support, please consider becoming a patron: "_You may get additional support_" tier.

**Comment by yomotsu** [comment]
Closing due to lack of feedback.
