### ISSUE TITLE
Max Zoom

### ISSUE THREAD

**Issue by amcdnl** [yomotsu/camera-controls#410]
### Describe the bug

When trying to implement the `maxZoom` property it doesn't seem to work. I've set 100 to 10000 and no difference. You can reproduce this in any of the demos and trying zooming with the mouse.

### To Reproduce

1. Go to https://codesandbox.io/s/sew669
2. Add `maxZoom` and set any level
3. Zoom in via mouse wheel
4. Note that it doesn't ever stop the zoom

### Expected behavior

The maxZoom would be honored

### Device

Desktop

### OS

MacOS

### Browser

Chrome

**Comment by yomotsu** [comment]
Would you mind providing a simplified demo to reproduce the problem exclusively?

Also, you may actually be changing the dolly distance with the mouse wheel, rather than the zoom level.
If you mean dolly distance, min/maxDistance should work.

see: https://github.com/yomotsu/camera-controls#dolly-vs-zoom

**Comment by amcdnl** [comment]
Dolly is what I needed - thanks!
