### ISSUE TITLE
Add method to retrieve spherical coordinates

### ISSUE THREAD

**Issue by krispya** [yomotsu/camera-controls#426]
### Is your feature request related to a problem? Please describe.

I am using camera-controls in an ECS with a pipe of camera systems. Each does not have knowledge of the other with the last system running `update` to commit all the changes. Because of this modular setup, each system pulls the position from the `CameraControls` instance to use it for new calculations:
```js
controls.getPosition(position);
```
However, some of them need to use spherical coordinates, such as a spherical camera shake system. In this case I am having to convert back to spherical:
```js
sphericalPosition.setFromVector3(position);
```
This is a waste of computation since the position is originally stored on the `CameraControls` instance as a `Spherical` instance. When looping over enough cameras, this can add up per frame.

### Describe the solution you'd like

It would be great to have a `getSpherical` method that just copies the internal spherical instance to a user one passed in. This would be very fast.
```js
const sphericalPosition = new THREE.Spherical()
controls.getSpherical(sphericalPosition)
```

**Comment by yomotsu** [comment]
@krispya 

Thanks for your request. I understand and seems it useful for some cases.
Let's add the method!

Would you like to make a PR or may I add the feature instead?

**Comment by yomotsu** [comment]
I just remember there are already similar getters
- `.distance`
- `.polarAngle`
- `.azimuthAngle`

therefore, you can do:
```ts
const sphericalPosition = new THREE.Spherical();
sphericalPosition.set(
  cameraControls.distance,
  cameraControls.polarAngle,
  cameraControls.azimuthAngle,
);
```

Does it look good?

**Comment by krispya** [comment]
I tried this but it doesn't work in my case because I have no called `update` yet and these values were only correct after `update` was called. `getPosition` allows me to use `setPosition` from one system and then before `update` is called, modify position again from another system.

**Comment by yomotsu** [comment]
Thanks for your notice.
I understand.

in the CC, there are 2 types of states for every value,
like, `distance` and `distanceEnd`, `polarAngle` and `polarAngleEnd`, and so on.

- `.distance` (without `End`) will return the current `distance`, which will be updated by `update()`.
  `.distance` will get closer to `distanceEnd` in every `update()`
- `.distanceEnd` is the goal point of the `.distance`, and will be set by every methods, user-drag or so.

Thus, when we need the param w/o End, CC must be updated by `update()` as you mentioned.
Then, CC can achieve smooth animation by 2 values.

`getPosition( out )` is actually computed by the `***End` values.
therefore, getPosition doesn't need `update()`. however, the return value is actually not the same as the CURRENT position, because that is the goal point.

is that okay to expose the end value for you?
if you need the actual current value, you may need the value without `End`, which needs to be updated.

**Comment by krispya** [comment]
Yes, I think exposing the end values helps me so that I can modify the end the value in a sequence before starting the animation. I think it is good to be explicit. I think either have a `getSpherical` and `getSphericalEnd` so that a user can get exactly the value they want or make it a param option like `getSpherical(sphericalPosition, true)` where `true` is end and `false` is current, `true` by default.

**Comment by yomotsu** [comment]
> where true is end and false is current, true by default.

Thanks for the suggestion. That would be nice!
I was looking for how we can hide the word "end" from users because the name "end" might be changed in a future update.

`getPosition()` and others can have the boolean as well!

I will add `getSpherical` with the boolean tonight

**Comment by yomotsu** [comment]
v2.5.0 was just released and `getPosition( out )` is available now!

**Comment by yomotsu** [comment]
let me close this issue by merging #430
